#Octomap Parameters
octo/tfFrame: /map
octo/robotFrame: /base_link
octo/resolution: 0.35
octo/probabilityHit: 0.65
octo/probabilityMiss: 0.4
octo/thresholdMin: 0.12
octo/thresholdMax: 0.97
octo/thresholdOccupancy: 0.7
octo/filterSpeckles: true
octo/maxFreeSpace: 0.0
octo/minHeightFreeSpace: 0.0
octo/sensorMaxRange: 15.0
octo/visualizeMinZ: -25.0
octo/visualizeMaxZ: 2
octo/mapPublishFrequency: 0.5
octo/treatUnknownAsOccupied: false
octo/changeDetectionEnabled: false
octo/velodyne_cloud_topic: /full_cloud_projected
